spring.application.name=projet_encheres
spring.messages.basename=messages
spring.messages.encoding=UTF-8

#Mise en place de la sécurité
spring.security.user.name=admin
spring.security.user.password=admin123

#Connexion à la base de données
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=encheres;integratedSecurity=false;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=P@ssw0rd


#Détail des requêtes pour le développement
logging.level.org.springframework.jdbc.core=TRACE


